### ISSUE TITLE
I put the plugin in but nothing happens help pls

### ISSUE THREAD

**Issue by critzydev** [DWalz/SCPSL-InventoryAccess#5]
I put the plugin in but nothing happens help pls

**Comment by DWalz** [comment]
Hey, thank you for your interest in this plugin. I do appreciate everyone using it. I do want it to be noted that this plugin was build for an old version of EXILED and therefor I can not really offer any advanced help regarding current versions of EXILED.

I stopped updating this plugin because there is an actively maintained alternative available [here (https://github.com/Parkeymon/RemoteKeycard)](https://github.com/Parkeymon/RemoteKeycard). 

I apologize for not having marked this project as obsolete. I kinda forgot it existed because it only ever was meant to be a private plugin for my SCP:SL group that others could use if they found it useful.

If you really want to use this plugin:
I can't really debug that easily from afar. If you put the plugin into the server plugins do make sure the server starts and look into the console if the plugin is being loaded. If you need help with that you can paste your log here. I do not plan on updating the plugin to EXILED 5 unless there is demand. 😉

**Comment by critzydev** [comment]
Thank you for responding. I did some research and found out why it didn’t work. I did find that other plugin that did work. But if you have other projects/plugins you are working on I would really like to take a look at them (When they are finished) or if you have finished projects as plugins for SCP:SL really interests me and It would be awesome to customize my upcoming server with my friends.

Also, I would like to mention that websites like Fiverr do not have any coders listed on them. If you would be willing to make a special type of plugin for our server for money. Ofc I fully understand if you are not interested in this at all. Tho I have been looking around for this type of plugin and since they haven’t been updated or just been stopped working on. We really want to find someone who could make one for us.

Again thanks for responding!

**Comment by DWalz** [comment]
Hey, I had some projects back in the days but I haven't touched EXILED in quite some time. If you have any plugin ideas you found interesting, I would like to use the chance to get into it. You can also take a look at the plugins featured in the official EXILED discord.

For future conversation and to keep this issue clear, you can reach me on Discord (`Lone Lunatic#6001`).
